### ISSUE TITLE
fix linter issues

### ISSUE THREAD

**Issue by ivancorrales** [wesovilabs-tools/orion-plugin-assert#2]
**Is your feature request related to a problem? Please describe.**
There're several inter issues

**Describe the solution you'd like**
Linter issues should be fixed.

**Additional context**
Linters checks must be passed as part of the CI pipeline. The project will make use of **golangci** and It will make use of the below configuration:
````
linters:
  enable-all: true
  disable:
    - wsl
    - forbidigo
    - gochecknoglobals
    - nlreturn
```
